export enum CallStatus{
    CREATED = 'CREATED',
    QUEUED="QUEUED",
    RINGING="RINGING",
    IN_PROGRESS="IN_PROGRESS",
    BUSY="BUSY",
    FAILED="FAILED",
    NO_ANSWER="NO_ANSWER",
    INITIATED = 'INITIATED',
    COMPLETED = 'COMPLETED',
    TRANSCRIPTED = 'TRANSCRIPTED'
}
