name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to AWS Lightsail
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /home/ubuntu/memories-api
          git pull origin main
          npm install --production
          pm2 restart backend || pm2 start server.js --name backend
