name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }} 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ckeck AWS SSH Key
        run: |
            echo " host: ${{ vars.AWS_HOST }}"
            echo " username: ${{ vars.AWS_USER }} "
            echo " key: ${{ secrets.AWS_SSH_KEY }} "    

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.AWS_HOST }}
          username: ${{ vars.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            set -e
            echo "Deploying application..."

            # Init the project directory
            rm ~/.pm2/logs/backend-error.log 
            rm ~/.pm2/logs/backend-out.log 
            PROJECT_DIR="/home/ubuntu/memories-api"
            if [ -d "$PROJECT_DIR" ]; then
              rm -rf $PROJECT_DIR
            fi

            # Give auth to clone
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            # Clone repository
            git clone git@github.com:wynsmic/memories-api.git $PROJECT_DIR
            cd $PROJECT_DIR

            # Install dependencies & build project
            npm install
            npm run build


            echo "Writing environment file..."
            NODE_ENV="${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}"
            mkdir -p ./config
            cat <<EOF > ./config/.${NODE_ENV}.env
            MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}
            NODE_ENV=${NODE_ENV}
            SERVER_PORT=${{ vars.SERVER_PORT }}
            WEBAPP_CLIENT_URL=${{ vars.WEBAPP_CLIENT_URL }}
            EOF

            # Restart PM2 process
            pm2 restart backend || pm2 start /home/ubuntu/memories-api/dist/server.js --name backend

      - name: Deployment Completed
        run: |
          echo "Deployment to $(echo $GITHUB_REF | sed 's/refs\/heads\///') complete!"
